### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by tanakamapondera** [ButterCMS/buttercms-marketing-site-nextjs-react#8]
I just cloned the repo down, installed all the dependencies, added the buttercms api key and ran "yarn dev" but the app won't run. I get the following error message:

$ yarn dev
yarn run v1.22.0
$ next
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
Warning: Built-in CSS support is being disabled due to custom CSS configuration
being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

> Using external babel configuration
> Location: "C:\Users\TANAKA\Desktop\buttercms-marketing-site-nextjs-react\.babe
lrc"
[ ready ] compiled successfully - ready on http://localhost:3000
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
Warning: the `Container` in `_app` has been deprecated and should be removed. ht
tps://err.sh/zeit/next.js/app-container-deprecated
TypeError: Cannot read property 'map' of undefined
    at Footer (C:\Users\TANAKA\Desktop\buttercms-marketing-site-nextjs-react\.ne
xt\server\static\development\pages\index.js:2525:35)

Has anybody else come across this error?
FYI: This is a fresh clone from master branch & I have no changed anything to the code

**Comment by ghoshnirmalya** [comment]
Step 1: Clone the application using `git clone https://github.com/ButterCMS/buttercms-marketing-site-nextjs-react`
Step 2: Install the dependencies using `yarn install`
Step 3: Create a **.env** file and add your ButterCMS API key inside it. It should be something like `BUTTER_CMS_API_KEY=something`
Step 4: Start your development server using `yarn dev`

The application should be up and running on [http://localhost:3000/](http://localhost:3000/). I followed the same steps and it seemed to worked perfectly fine.

**Comment by jakelumetta** [comment]
@tanakamapondera please let us know if this works for you

**Comment by tanakamapondera** [comment]
@ghoshnirmalya Sure but what do you mean by that? Screenshot what I have setup in ButterCMS?

**Comment by ghoshnirmalya** [comment]
@tanakamapondera By that I mean the data that ButterCMS is sending you when you're doing a request to its server.

**Comment by tanakamapondera** [comment]
@ghoshnirmalya 
Using the postman test provided by ButterCMS, I get data back from the server just fine actually.
Posts:
![posts](https://user-images.githubusercontent.com/43476830/84779285-35361e00-afb2-11ea-85fb-910a34027a54.PNG)
Pages:
![faqs](https://user-images.githubusercontent.com/43476830/84779318-3ff0b300-afb2-11ea-9363-7afd2aa178cb.PNG)

I rechecked all my naming conventions and it looks like I had the wrong slug on one of the pages. So the "loading" error is gone but a new "map" error is now showing
![error 2](https://user-images.githubusercontent.com/43476830/84778768-75e16780-afb1-11ea-8c40-c459bdb69a46.PNG)

**Comment by ghoshnirmalya** [comment]
@tanakamapondera Can you log this request in your browser through code and send me a screenshot? I understand that Postman is fetching the data. However, I need to understand if the data is getting fetched from the browser or not.

**Comment by tanakamapondera** [comment]
@ghoshnirmalya My apologies, here are the screenshots:
Blog Posts:
![Screenshot (101)](https://user-images.githubusercontent.com/43476830/84782702-5a2c9000-afb6-11ea-8f63-6c9001e9ffad.png)

Page:
![Screenshot (102)](https://user-images.githubusercontent.com/43476830/84782730-60227100-afb6-11ea-8150-77d1f8258cf9.png)

**Comment by tanakamapondera** [comment]
@ghoshnirmalya So after a bit of reverse engineering, I finally have my site running locally and data is being pulled in from ButterCMS:
![home](https://user-images.githubusercontent.com/43476830/84805909-f82e5380-afd2-11ea-94bb-fa13b62f33fe.PNG)

But I have identified 2 blockers:
1) NextJS does not like the "style.css" file, needs to be properly configured:
![css](https://user-images.githubusercontent.com/43476830/84806316-7e4a9a00-afd3-11ea-84e0-42d4490499bc.PNG)

Also, there is an issue with the footer component:
![error 2](https://user-images.githubusercontent.com/43476830/84806426-aafeb180-afd3-11ea-8cf6-c44cfe806bf3.PNG)

Once I remove those two files, everything compiles successfully though. Did you every come across these errors?

**Comment by ghoshnirmalya** [comment]
@tanakamapondera 

1. The latest version of Next.js [supports CSS out of box](https://nextjs.org/docs/basic-features/built-in-css-support). You might need to update the version of Next.js to resolve this issue.

2. For this issue, I think that `navigation_links` is coming as `undefined` from your API

**Comment by tanakamapondera** [comment]
@ghoshnirmalya 
Makes sense, 1) has been solved.
Lastly, how did you setup `navigation_links`? Is it possible to get a screenshot of the page setup in Butter? That wasn't covered in the tutorial that I am following: [Full CMS with ButterCMS & Next JS](https://buttercms.com/blog/build-a-cms-powered-marketing-site-while-avoiding-wordpress)

Again, thank you very much for your help!

**Comment by tanakamapondera** [comment]
@ghoshnirmalya As long as I don't use the footer element, then everything works. I think that's what I'll do for now until I figure out whats wrong

**Comment by jakelumetta** [comment]
Thanks @ghoshnirmalya !   @tanakamapondera Let me know if you have any other issues / questions. Happy to help.
